dist: bionic

language: rust

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry
    
before_install:
  - nvm install 12  # needed for scripts/_scripts/markdown/validate-link-refs.js

install:
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt

jobs:
  fast_finish: true

  include:
    - name: "Stable"
      if: type != pull_request
      rust: stable
      env: CHANNEL="stable"
    - name: "Beta"
      if: type != pull_request
      rust: beta
      env: CHANNEL="beta"
    - name: "Nightly"
      if: type != pull_request
      rust: nightly
      env: CHANNEL="nightly"

    - name: "Squashed commits"
      if: type = pull_request
      env: BRANCH="origin/$TRAVIS_PULL_REQUEST_BRANCH"
      script:
        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        - git fetch origin
        - BRANCH=base scripts/squashed

    - name: "Linux release"
      if: tag IS present
      rust: stable
      os: linux
      env: CHANNEL="stable"
    - name: "MacOS release"
      if: tag IS present
      rust: stable
      os: osx
      env: CHANNEL="stable"

# If more needs to be added here, it should be added to ladder.
script: ./ladder ensure

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ "$CHANNEL" == "stable" ]; then
        export DEPLOY_UI=1
        scripts/build_www
      elif [ "$CHANNEL" == "nightly" ]; then
        cargo doc --no-deps --target-dir docs-public
        cargo doc --document-private-items --no-deps --target-dir docs-internal
        export DEPLOY_DOCS=1
      fi
    fi
    if [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      cargo build --release
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        mv target/release/slide slide-x86_64-linux
        export DEPLOY_FILE="slide-x86_64-linux"
      else
        mv target/release/slide slide-x86_64-apple-darwin
        export DEPLOY_FILE="slide-x86_64-apple-darwin"
      fi
    fi

DOCS_DEPLOY_DEFAULTS: &docs_deploy_defaults
  provider: pages:git
  edge: true
  token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  project_name: slide
  name: slide-bot
  email: vcaa1729@gmail.com
  committer_from_gh: true
  deployment_file: true

deploy:
  # Documentation:public
  - <<: *docs_deploy_defaults
    repo: yslide/docs
    target_branch: master
    local_dir: docs-public/doc
    on:
      condition: $DEPLOY_DOCS = 1
  # Documentation:internal
  - <<: *docs_deploy_defaults
    repo: yslide/internals
    target_branch: master
    local_dir: docs-internal/doc
    on:
      condition: $DEPLOY_DOCS = 1
  # Web UI
  - <<: *docs_deploy_defaults
    repo: yslide/yslide.github.io
    target_branch: master
    local_dir: www/
    on:
      condition: $DEPLOY_UI = 1
  # Binary releases
  - provider: releases
    edge: true
    token: $GITHUB_TOKEN
    file: $DEPLOY_FILE
    on:
      tags: true
    run: ./scripts/publish
